[package]
name = "rvr-isa"
description = "RISC-V instruction set definitions, decoder, and lifter"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
thiserror.workspace = true
rayon.workspace = true
rvr-ir.workspace = true
